### ISSUE TITLE
"italic inversion" rules for .normal, .italics

### ISSUE THREAD

**Issue by pkra** [FriendsOfEpub/Blitz#23] opened 2018-11-14 10:38 UTC
I was recently in a situation where I had to add `.normal` to a `<blockquote>` which led me to add a "inverted" copy of
https://github.com/FriendsOfEpub/Blitz/blob/01b95fc11543fa2de87102fca2f0c68727b363f9/Blitz_framework/CSS/blitz.css#L247-L255
For good measure, I did the same for https://github.com/FriendsOfEpub/Blitz/blob/01b95fc11543fa2de87102fca2f0c68727b363f9/Blitz_framework/CSS/blitz.css#L278-L296

when using `.normal` or `.italics`.

I was wondering if you're interested in that or if it's too much of an edgecase.

**Comment by JayPanoz** [comment] 2018-11-14 11:33
Hmmm that’s certainly not an edge-case but I’d consider it kinda raises an overarching issue.

Not that I haven’t considered it an issue for a while… I’ve never really been satisfied with the current LESS architecture – or, more simply, the directory structure –: [`Typo` is indeed meant as a default you can customise](https://github.com/FriendsOfEpub/Blitz/blob/master/Blitz_framework/LESS/base/typo.less) but since it’s hidden in the hierarchy, it may well not convey that idea at all right now, esp. as the filename is not something like `custom` or something. 

I refrained from changing that because that would be a breaking change. But well, I guess I can create a release and tell people to stick to the one that doesn’t break anything if this is an issue?

**Comment by pkra** [comment] 2018-11-14 13:58
I have not really dived into the Less setup (for lack of Less experience).

> : Typo is indeed meant as a default you can customise

Just in case I was not explaining myself well: I don't want to customize all blockquotes to normal - I have both italic and normal blockquotes.

**Comment by JayPanoz** [comment] 2018-11-14 15:08
Oh no worries that is exactly what I understood. 

What I was trying to poorly say is that this part is just a default you can build upon/modify i.e. selectors are primarily simple HTML elements (with a specificity of 0001) with default rules for the sake of having a default output, and nothing (much) else.

So users are indeed encouraged to modify those and/or add their own styles on top of it as it was designed for this purpose in the first place. 

In hindsight though, I really don’t like the way we’re doing defaults, esp. as most people are probably using the CSS output with all the functional classes.

At some point we envisioned LESS Presets (cf. [to-do list](https://github.com/FriendsOfEpub/Blitz#to-do)), which would have been customisation of this exact file in order to output “themes” for say non-fiction, cookbooks, essays education and so on and so forth, types for which we would probably end up with (maybe more semantic) classes differentiating lists, block quotes, etc. as you’ve done.

So in absolute terms, that could probably fit a lot better in such a theme.

**Comment by JayPanoz** [comment] 2020-02-14 12:48
Given the Blitz project is under an “End of Life process”, this issue has been frozen, labeled `documentation` and `wontfix`, and won’t be addressed any further. Please check #66 for more details.

**Closed** 2020-05-11 17:48 UTC
Labels: documentation, wontfix
